# Generated by Django 5.1.7 on 2025-03-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempt',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
