# Generated by Django 5.1.7 on 2025-03-17 02:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0003_test_time_limit_per_question_test_total_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='microphone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='network',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
