# Generated by Django 5.1.7 on 2025-03-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0004_testattempt_location_testattempt_microphone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
