# Generated by Django 5.1.7 on 2025-03-18 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0005_testattempt_total_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
