# Generated by Django 5.1.7 on 2025-03-19 01:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0006_remove_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('test_title', models.CharField(max_length=255)),
                ('attempted_test_id', models.CharField(max_length=255)),
                ('attempt_date', models.DateTimeField()),
                ('total_score', models.FloatField()),
                ('total_questions', models.IntegerField()),
                ('time_taken', models.DurationField()),
                ('passed', models.BooleanField()),
                ('can_reattempt', models.BooleanField()),
                ('answers', models.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name='completedtest',
            old_name='title',
            new_name='test_name',
        ),
        migrations.RemoveField(
            model_name='completedtest',
            name='highest_score',
        ),
        migrations.RemoveField(
            model_name='completedtest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='completedtest',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='recentactivity',
            name='created_at',
        ),
        migrations.AddField(
            model_name='completedtest',
            name='test_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recentactivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='improvement',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='status',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recentactivity',
            name='details',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='PerformanceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PerformanceStats',
        ),
    ]
