# Generated by Django 5.1.7 on 2025-03-19 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0007_performancehistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancehistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
