# Generated by Django 5.1.7 on 2025-03-19 02:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0008_performancehistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='date_earned',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='description',
        ),
        migrations.AddField(
            model_name='achievement',
            name='awarded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
