# Generated by Django 5.1.7 on 2025-03-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0009_remove_achievement_date_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='certificates_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='highest_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
