# Generated by Django 5.1.7 on 2025-03-19 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0010_testattempt_accuracy_testattempt_certificates_earned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attemptedtest',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='attemptedtest',
            name='score',
        ),
        migrations.AddField(
            model_name='attemptedtest',
            name='max_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='attemptedtest',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attemptedtest',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attemptedtest',
            name='subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attemptedtest',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attemptedtest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
