# Generated by Django 5.1.7 on 2025-03-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0011_rename_timestamp_attemptedtest_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptedtest',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attemptedtest',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=10),
        ),
    ]
