# Generated by Django 5.1.7 on 2025-03-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0012_attemptedtest_score_alter_attemptedtest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempt',
            name='status',
            field=models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('in_progress', 'In Progress')], default='in_progress', max_length=100),
        ),
    ]
