# Generated by Django 5.1.7 on 2025-03-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0014_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
