# Generated by Django 5.1.7 on 2025-03-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0017_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
