# Generated by Django 5.1.7 on 2025-03-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0023_announcement_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptedtest',
            name='score',
        ),
        migrations.RemoveField(
            model_name='attemptedtest',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='attemptedtest',
            name='title',
        ),
        migrations.AddField(
            model_name='attemptedtest',
            name='accuracy',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attemptedtest',
            name='certificates_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attemptedtest',
            name='max_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='attemptedtest',
            name='status',
            field=models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=10),
        ),
    ]
