# Generated by Django 5.1.7 on 2025-03-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0024_remove_attemptedtest_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptedtest',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='attemptedtest',
            name='certificates_earned',
        ),
        migrations.AddField(
            model_name='attemptedtest',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attemptedtest',
            name='subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attemptedtest',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attemptedtest',
            name='max_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='attemptedtest',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=10),
        ),
    ]
