# Generated by Django 5.1.7 on 2025-03-25 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0025_remove_attemptedtest_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptedtest',
            name='status',
            field=models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], default='ongoing', max_length=10),
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='improvement',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='status',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='test_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
