# Generated by Django 5.1.7 on 2025-03-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0027_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
