# Generated by Django 5.1.7 on 2025-03-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0028_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
