# Generated by Django 5.1.7 on 2025-04-22 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0030_alter_test_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='isDuplicated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='notification_emails',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='test',
            name='receive_email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='AllowedParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_participants', to='jango.test')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='captures/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('validation_message', models.CharField(blank=True, max_length=255)),
                ('face_detected', models.BooleanField(default=False)),
                ('multiple_faces', models.BooleanField(default=False)),
                ('looking_straight', models.BooleanField(default=False)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
