# Generated by Django 5.2 on 2025-04-24 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0030_test_isduplicated_test_notification_emails_and_more'),
    ]

    operations = [
        #migrations.CreateModel(
             #name='AllowedParticipant',
             #fields=[
                 #('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # ('email', models.EmailField(max_length=254)),
                # ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_participants', to='jango.test')),
             #],
        # ),
        # migrations.CreateModel(
          #   name='StudentCapture',
           #  fields=[
               #  ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
               #  ('image', models.ImageField(upload_to='captures/')),
               #  ('timestamp', models.DateTimeField(auto_now_add=True)),
                # ('is_valid', models.BooleanField(default=False)),
                # ('validation_message', models.CharField(blank=True, max_length=255)),
                # ('face_detected', models.BooleanField(default=False)),
                # ('multiple_faces', models.BooleanField(default=False)),
                # ('looking_straight', models.BooleanField(default=False)),
                # ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            # ],
            # options={
              #   'ordering': ['-timestamp'],
            # },
       #  ),
    ]
