# Generated by Django 5.1.7 on 2025-04-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0030_alter_test_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='isDuplicated',
            field=models.BooleanField(default=False),
        ),
    ]
