# Generated by Django 5.2 on 2025-04-25 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0032_allowedparticipant_studentcapture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='date',
        ),
    ]
