# Generated by Django 5.1.7 on 2025-04-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0032_remove_test_isduplicated_test_notification_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='isDuplicated',
            field=models.BooleanField(default=False),
        ),
    ]
